In [1]:
cwd

NameError: name 'cwd' is not defined

In [2]:
pwd

u'C:\\Anaconda2'

In [3]:
import numpy as np


In [4]:
my_list = [1,2,3,4]


In [5]:
my_array1 = np.array(my_list)


In [6]:
my_array1


array([1, 2, 3, 4])

In [7]:
my_list2 = [11,22,33,44]


In [8]:
my_lists = [my_list, my_list2]


In [9]:
my_lists


[[1, 2, 3, 4], [11, 22, 33, 44]]

In [10]:
my_array2 = np.array(my_lists)

In [11]:
my_array2.shape

(2L, 4L)

In [12]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [13]:
my_array2.dtype

dtype('int32')

In [14]:
np.zeros(5)


array([ 0.,  0.,  0.,  0.,  0.])

In [15]:
np.ones([5,5])


array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [16]:
np.empty(5)


array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
np.eye(5)


array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [18]:
np.arange(5)


array([0, 1, 2, 3, 4])

In [19]:
np.arange([5,50,2])


TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [20]:
np.arange(5,50,2)


array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])